name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - master

jobs:
  check:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Lint pod
        run: pod lib lint
