name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Lint pod
        run: pod lib lint
