name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - master

jobs:
  check:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Test macOS
        run: swift test
      - name: Test iOS
        run: |
         swift package generate-xcodeproj --output temp && cd temp
         xcodebuild build -sdk iphoneos -scheme 'MarkdownKit-Package'
         xcodebuild test -destination 'name=iPhone 12' -scheme 'MarkdownKit-Package'
         cd .. && rm -r temp
      - name: Lint pod
        run: pod lib lint
